### ISSUE TITLE
React JS Kullanımı

### ISSUE THREAD

**Issue by mertbuldur** [iyzico/iyzipay-node#101]
Merhabalar , React JS ile iyzico kullanabiliyor muyuz ? alt tarafta laravel kullanıp back endden ödeme yaptırmaya çalıştım ama paymentURL nedeniyle geri back end e döndü. iyzipay-node zaten fs olmadığı için çalışmıyor react js kullanan varmı ödemeler için ?

**Comment by HalilAlgan** [comment]
Merhaba

> Kullanabiliyorsun, dökümantasyonda yazılanı uyguladıktan sonra frontend tarafına dönen response daki scripti html-react-parser ile parse edip çalıştırman gerekiyor

Merhaba, ben backend`de spring boot ve frontend`de reactjs kullaniyorum. Iyzipay`in java versiyonunu kullanmak istiyorum ama backend tarafina "localhost:8080/payment/iyzicoPayment" istegini gonderdigim zaman   bana bu hatayi veriyor backend: "2022-09-28 19:13:37.316 ERROR 4608 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [payment/iyzicoPayment], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause" . Acaba backendde frontend url`sini (localhost:3000) belirtmem falan mi gerekiyor. Tesekkurler.

**Comment by talhacetin01** [comment]
> Kullanabiliyorsun, dökümantasyonda yazılanı uyguladıktan sonra frontend tarafına dönen response daki scripti html-react-parser ile parse edip çalıştırman gerekiyor

Merhaba, script'i parse ettikten sonra nasil calistirabiliriz?
